
USE [master]
GO

/****** Object:  Database [onramp]    Script Date: 8/16/2019 3:27:33 PM ******/
CREATE DATABASE [onramp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'onramp_data', FILENAME = N'D:\SQL_2012\onramp_data.mdf' , SIZE = 3136KB , MAXSIZE = 5120000KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'onramp_log', FILENAME = N'D:\SQL_2012\onramp_log.ldf' , SIZE = 1024KB , MAXSIZE = 5120000KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [onramp] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [onramp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [onramp] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [onramp] SET ANSI_NULLS OFF
GO

ALTER DATABASE [onramp] SET ANSI_PADDING OFF
GO

ALTER DATABASE [onramp] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [onramp] SET ARITHABORT OFF
GO

ALTER DATABASE [onramp] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [onramp] SET AUTO_CREATE_STATISTICS ON
GO

ALTER DATABASE [onramp] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [onramp] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [onramp] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [onramp] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [onramp] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [onramp] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [onramp] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [onramp] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [onramp] SET  ENABLE_BROKER
GO

ALTER DATABASE [onramp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [onramp] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [onramp] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [onramp] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [onramp] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [onramp] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [onramp] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [onramp] SET RECOVERY FULL
GO

ALTER DATABASE [onramp] SET  MULTI_USER
GO

ALTER DATABASE [onramp] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [onramp] SET DB_CHAINING OFF
GO

ALTER DATABASE [onramp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [onramp] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

EXEC sys.sp_db_vardecimal_storage_format N'onramp', N'ON'
GO

USE [onramp]
GO

/****** Object:  Table [dbo].[Tbl_Customers]    Script Date: 8/16/2019 3:27:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Tbl_Orders]    Script Date: 8/16/2019 3:27:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Tbl_Product_Category]    Script Date: 8/16/2019 3:27:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Tbl_Products]    Script Date: 8/16/2019 3:27:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Tbl_Suppliers]    Script Date: 8/16/2019 3:27:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

USE [master]
GO

ALTER DATABASE [onramp] SET  READ_WRITE
GO

USE [master]
GO

/****** Object:  Database [onramp]    Script Date: 8/19/2019 5:15:13 PM ******/
CREATE DATABASE [onramp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'onramp_data', FILENAME = N'D:\SQL_2012\onramp_data.mdf' , SIZE = 3136KB , MAXSIZE = 5120000KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'onramp_log', FILENAME = N'D:\SQL_2012\onramp_log.ldf' , SIZE = 1024KB , MAXSIZE = 5120000KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [onramp] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [onramp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [onramp] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [onramp] SET ANSI_NULLS OFF
GO

ALTER DATABASE [onramp] SET ANSI_PADDING OFF
GO

ALTER DATABASE [onramp] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [onramp] SET ARITHABORT OFF
GO

ALTER DATABASE [onramp] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [onramp] SET AUTO_CREATE_STATISTICS ON
GO

ALTER DATABASE [onramp] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [onramp] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [onramp] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [onramp] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [onramp] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [onramp] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [onramp] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [onramp] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [onramp] SET  ENABLE_BROKER
GO

ALTER DATABASE [onramp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [onramp] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [onramp] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [onramp] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [onramp] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [onramp] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [onramp] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [onramp] SET RECOVERY FULL
GO

ALTER DATABASE [onramp] SET  MULTI_USER
GO

ALTER DATABASE [onramp] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [onramp] SET DB_CHAINING OFF
GO

ALTER DATABASE [onramp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [onramp] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

EXEC sys.sp_db_vardecimal_storage_format N'onramp', N'ON'
GO

USE [onramp]
GO

/****** Object:  Table [dbo].[Tbl_Customers]    Script Date: 8/19/2019 5:15:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Tbl_Orders]    Script Date: 8/19/2019 5:15:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Tbl_Product_Category]    Script Date: 8/19/2019 5:15:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Tbl_Products]    Script Date: 8/19/2019 5:15:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Tbl_Suppliers]    Script Date: 8/19/2019 5:15:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

USE [master]
GO

ALTER DATABASE [onramp] SET  READ_WRITE
GO
