//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRamp.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Suppliers
    {
        public int Supplier_ID { get; set; }
        public string Supplier_Name { get; set; }
        public string Supplier_Email { get; set; }
        public string Supplier_Telephone_Number { get; set; }
    }
}
