//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRamp.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Products()
        {
            this.Tbl_Orders = new HashSet<Tbl_Orders>();
        }
    
        public int Product_Barcode { get; set; }
        public int Product_Category_ID { get; set; }
        public string Product_Name { get; set; }
        public System.DateTime Product_Date_Captured { get; set; }
        public int Supplier_ID { get; set; }
        public string Product_Location { get; set; }
        public Nullable<int> Product_Warranty { get; set; }
        public Nullable<int> Product_Status { get; set; }
    
        public virtual Tbl_Product_Category Tbl_Product_Category { get; set; }
        public virtual Tbl_Suppliers Tbl_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Orders> Tbl_Orders { get; set; }
    }
}
