//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRamp.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Orders
    {
        public int Order_ID { get; set; }
        public string Order_Number { get; set; }
        public int Customer_ID { get; set; }
        public System.DateTime Date_Sold { get; set; }
        public bool Payment_Received { get; set; }
    
        public virtual Tbl_Customers Tbl_Customers { get; set; }
    }
}
